
# 6. CONVERT TO BUILDING CENTROID
# 7. READ OSM NETWORK
# 8. OUTPUT TO TEMP


# 7. READ OSM NETWORK
OSMnetwork <- networkLoader(net_dir)

# 6. CONVERT TO BUILDING CENTROID AND SNAP TO NEAREST NETWORK LINES
#    -> POINT ON SURFACE
#    -> SNAP BUILDING CENTROIDS TO NETWORK
# 8. OUTPUT TO TEMP
OSMbuildings_out <- OSMsnap(OSMbuildings, OSMnetwork)
